### ISSUE TITLE
add top-level options to configuration file, or specify a separate global config file

### ISSUE THREAD

**Issue by dmeliza** [melizalab/decide-rs#19]
Currently the config file (`components.yml`) just specifies the components in the apparatus at the top level, so it's not possible to specify any global options for the controller. We could restructure this file by moving components into their own array, e.g.

```yaml
ssdp-interface: eth0
components:
  house-lights:
    driver: Lights
    config:
       pin: 4
```

Or we could put top-level options in a separate file.
